### ISSUE TITLE
Fix issue of dimension of length 1 output from subsetter leading to error raised during stitchee

### ISSUE THREAD

**Issue by danielfromearth** [nasa/stitchee#140]
This error was discovered by @ank1m while testing the fix to a different, sorting-related, error in stitchee. Some discussion of it occurred in [this PR #136](https://github.com/danielfromearth/stitchee/pull/136#issuecomment-2025951037).

**Comment by ank1m** [comment]
This issue one is addressed and fixed in [#147](https://github.com/nasa/stitchee/issues/147)
