### ISSUE TITLE
Expand "empty" granule detection to include those with only all-null variables

### ISSUE THREAD

**Issue by danielfromearth** [nasa/stitchee#147]
## Problem

Currently, `stitchee` determines "emptiness" of input netCDF granules by inspecting the `.size` attribute of all variable arrays.  As soon as a size not equal to 0 is detected, the granule is considered non-empty. The logic is coded [here](https://github.com/nasa/stitchee/blob/1c05d338d38593beb0a803738dabd0b6e413e40b/concatenator/stitchee.py#L215).

@ank1m has discovered an edge case where an output netCDF from the level-2 subsetter can have only arrays of dimensions 1x1, with value NaN, for each variable.  By the current emptiness check in stitchee, this is not considered "empty".  Because it is not considered empty, the netCDF is included in the list of files to be concatenated and ultimately, this results in Stitchee raising an error when it calls on `xarray` to perform the concatenation.

## Desired behavior
A netCDF with only singleton, null-values, arrays should also be considered empty by stitchee.

## Implications for the Harmony service chain
The following diagram illustrates the impact of a netCDF with only singleton null-valued arrays (red-colored square) being passed from the level-2 subsetter to Stitchee. On the left is the current behavior, and on the right is the desired behavior.

![case_with_one_bad_granule_20240410](https://github.com/nasa/stitchee/assets/114174502/ebf68824-95f7-4a08-8684-fb35abf8ae00)

**Comment by ank1m** [comment]
This [PR #159](https://github.com/nasa/stitchee/pull/159) includes the fix for this issue.

**Comment by danielfromearth** [comment]
Resolved.
