### ISSUE TITLE
Handle case when one of the scans has **only one empty** granule, resulting in instance without any output file

### ISSUE THREAD

**Issue by danielfromearth** [nasa/stitchee#153]
> - The only error case remaining is when one of the scans has **only one empty** granule, resulting in instance without any output file: harmony proceeds with all other stitched files to concatenate them in *concise*

_Originally posted by @ank1m in https://github.com/nasa/stitchee/issues/152#issuecomment-2049996406_

**Comment by danielfromearth** [comment]
So, @ank1m, the pseudo logic for the new desired behavior is....

if (NumberOfGranules == 1) and (TheGranule is empty):
    copy TheGranule to OutputPath
    return OutputPath

Correct?

**Comment by ank1m** [comment]
For now, yes.
Two considerations:
- We have to test if having all-NaN file for input would breaks CONCISE or not
- If it doesn't break it, that means that output merged file would have a data layer full-of-NaNs, which seems like a strange choice (to be addressed after discussion with Harmony)
