### ISSUE TITLE
Improve handling of large (such as >1000) file orders

### ISSUE THREAD

**Issue by danielfromearth** [nasa/stitchee#169]
Perhaps by closing, or writing to file, the intermediate Dataset objects.

**Comment by cheyenneland** [comment]
Closed xarray dataset object and netCDF dataset object using try, except and finally statements on stitchee.py and had a successful run on the CERES Ordering Tool (more than 3000 files). Will need to do more tests without the try, except and finally statements for both to see if one of them is not needed.

**Comment by cheyenneland** [comment]
Took out the edited out the try, except and finally statements for the ncfile and only left it for the xarray dataset object and had a successful test on the CERES Ordering Tool.

**Comment by danielfromearth** [comment]
Closing this issue, because it appears to no longer be needed for working with CERES data. The overarching bundling process splits jobs into manageable groups of files which can be processed by stitchee without such modifications.
